export type BrowserLocatorText =
  | { type: 'string'; value: string }
  | { type: 'regexp'; source: string; flags?: string };

export type BrowserLocatorStep =
  | {
      type: 'getByRole';
      role: string;
      options?: {
        name?: BrowserLocatorText;
        exact?: boolean;
        checked?: boolean;
        disabled?: boolean;
        expanded?: boolean;
        selected?: boolean;
        pressed?: boolean;
        includeHidden?: boolean;
        level?: number;
      };
    }
  | {
      type: 'locator';
      selector: string;
    }
  | {
      type: 'getByText';
      text: BrowserLocatorText;
      options?: { exact?: boolean };
    }
  | {
      type: 'getByLabel';
      text: BrowserLocatorText;
      options?: { exact?: boolean };
    }
  | {
      type: 'getByPlaceholder';
      text: BrowserLocatorText;
      options?: { exact?: boolean };
    }
  | {
      type: 'getByAltText';
      text: BrowserLocatorText;
      options?: { exact?: boolean };
    }
  | {
      type: 'getByTitle';
      text: BrowserLocatorText;
      options?: { exact?: boolean };
    }
  | {
      type: 'getByTestId';
      text: BrowserLocatorText;
    }
  | {
      type: 'filter';
      options: { hasText?: BrowserLocatorText; has?: BrowserLocatorIR };
    }
  | { type: 'and'; locator: BrowserLocatorIR }
  | { type: 'or'; locator: BrowserLocatorIR }
  | { type: 'nth'; index: number }
  | { type: 'first' }
  | { type: 'last' };

export type BrowserLocatorIR = {
  steps: BrowserLocatorStep[];
};

export type BrowserRpcRequest = {
  id: string;
  /** Absolute test file path for locating runner iframe */
  testPath: string;
  /** Run identifier generated by container for stale-request protection. */
  runId: string;
  kind: 'locator' | 'expect';
  locator: BrowserLocatorIR;
  method: string;
  args: unknown[];
  /**
   * Negation for expect matchers (equivalent to Playwright expect(...).not).
   * Only meaningful for kind === 'expect'.
   */
  isNot?: boolean;
  /** Optional timeout override (ms). Falls back to browser rpcTimeout. */
  timeout?: number;
};

export type BrowserRpcResponse = {
  id: string;
  result?: unknown;
  error?: string;
};

/**
 * Snapshot RPC request from runner iframe.
 * The container will forward these to the host via WebSocket RPC.
 */
export type SnapshotRpcRequest =
  | {
      id: string;
      method: 'resolveSnapshotPath';
      args: { testPath: string };
    }
  | {
      id: string;
      method: 'readSnapshotFile';
      args: { filepath: string };
    }
  | {
      id: string;
      method: 'saveSnapshotFile';
      args: { filepath: string; content: string };
    }
  | {
      id: string;
      method: 'removeSnapshotFile';
      args: { filepath: string };
    };

/**
 * Snapshot RPC response from container to runner iframe.
 */
export type SnapshotRpcResponse = {
  id: string;
  result?: unknown;
  error?: string;
};
