import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'pathe';
import { describe, expect, it } from '@rstest/core';
import {
  BLOB_TRACK_MATCHES_RUNNER_EVENTS,
  BlobReporter,
  blobFileName,
  isBlobFile,
  parseBlobFile,
} from '../../src/reporter/blob';
import type { NormalizedConfig } from '../../src/types';

describe('blob wire-format', () => {
  it('records every runner lifecycle event on the track (compile guard)', () => {
    expect(BLOB_TRACK_MATCHES_RUNNER_EVENTS).toBe(true);
  });

  it('names the unsharded blob deterministically', () => {
    expect(blobFileName()).toBe('blob.json');
    expect(blobFileName(undefined)).toBe('blob.json');
  });

  it('encodes the shard index/count into the filename', () => {
    expect(blobFileName({ index: 1, count: 4 })).toBe('blob-1-4.json');
    expect(blobFileName({ index: 12, count: 30 })).toBe('blob-12-30.json');
  });

  it('round-trips: every name the writer emits is recognized by the reader', () => {
    expect(isBlobFile(blobFileName())).toBe(true);
    expect(isBlobFile(blobFileName({ index: 2, count: 3 }))).toBe(true);
  });

  it('names the file in the error for truncated or non-object content', () => {
    expect(() => parseBlobFile('{"version":"1', 'blob-1-2.json')).toThrow(
      /blob-1-2\.json.*not valid JSON/,
    );
    // `.*` tolerates the color escapes around the interpolated version.
    expect(() => parseBlobFile('null', 'blob.json')).toThrow(
      /generated by Rstest .*unknown/,
    );
  });

  it('rejects unrelated and malformed filenames', () => {
    expect(isBlobFile('blob.txt')).toBe(false);
    expect(isBlobFile('report.json')).toBe(false);
    expect(isBlobFile('blob-1.json')).toBe(false);
    expect(isBlobFile('blob-1-2-3.json')).toBe(false);
    expect(isBlobFile('prefix-blob.json')).toBe(false);
    expect(isBlobFile('blob-a-b.json')).toBe(false);
  });

  it('persists coverage setup context for deferred merging', async () => {
    const rootPath = mkdtempSync(join(tmpdir(), 'rstest-blob-'));
    const outputDir = join(rootPath, '.rstest-reports');
    const reporter = new BlobReporter({
      rootPath,
      config: {} as NormalizedConfig,
      options: { outputDir: '.rstest-reports' },
    });

    try {
      reporter.setCoverageContext({
        setupFiles: ['/workspace/.rstest-virtual/setup.mjs'],
        projects: ['browser'],
      });
      await reporter.onTestRunEnd({
        results: [],
        testResults: [],
        duration: { totalTime: 0, buildTime: 0, testTime: 0 },
        snapshotSummary: {
          added: 0,
          didUpdate: false,
          failure: false,
          filesAdded: 0,
          filesRemoved: 0,
          filesRemovedList: [],
          filesUnmatched: 0,
          filesUpdated: 0,
          matched: 0,
          total: 0,
          unchecked: 0,
          uncheckedKeysByFile: [],
          unmatched: 0,
          updated: 0,
        },
      });

      const blob = JSON.parse(
        readFileSync(join(outputDir, 'blob.json'), 'utf8'),
      );
      expect(blob.setupFiles).toEqual(['/workspace/.rstest-virtual/setup.mjs']);
      expect(blob.projects).toEqual(['browser']);
    } finally {
      rmSync(rootPath, { recursive: true, force: true });
    }
  });
});
