import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'pathe';
import type {
  CoverageMapData,
  Duration,
  NormalizedConfig,
  Reporter,
  ShardConfig,
  SnapshotSummary,
  TestCaseInfo,
  TestFileInfo,
  TestFileResult,
  TestInfo,
  TestResult,
  TestSuiteInfo,
  UserConsoleLog,
} from '../types';
import type { BlobReporterOptions } from '../types/reporter';
import { color } from '../utils';

/**
 * One recorded lifecycle event, in the order the run emitted it. A payload the
 * blob already stores for its own reasons is referenced by `testId` — the
 * collected tree for the start events, `BlobData.results` for a case result;
 * a payload nothing else stores is inlined here.
 */
export type BlobFileEvent =
  | { h: 'ready' }
  | { h: 'suiteStart' | 'caseStart' | 'caseResult'; id: string }
  | { h: 'suiteResult'; result: TestResult }
  | { h: 'log'; log: UserConsoleLog };

/**
 * Per-file data that `TestFileResult` cannot carry: `results` holds case
 * results only, with no collected tree and no record of the order any of it
 * was reported in.
 *
 * `events` is the authority for replay. Reconstructing an order from `tests`
 * instead would serialize what `concurrent` siblings interleaved, and would
 * hoist a suite's `afterAll` output above the child results it followed.
 */
export type BlobFileData = {
  tests: TestInfo[];
  events: BlobFileEvent[];
};

export type BlobData = {
  version: string;
  shard?: ShardConfig;
  results: TestFileResult[];
  coverage?: CoverageMapData;
  testResults: TestResult[];
  duration: Duration;
  snapshotSummary: SnapshotSummary;
  unhandledErrors?: { message: string; stack?: string; name?: string }[];
  /**
   * Output that could not be attributed to a file window (no `project` on the
   * log). Everything else lives on its file's replay track instead, so the two
   * never hold the same log twice.
   */
  consoleLogs?: UserConsoleLog[];
  /** Keyed by {@link blobFileKey}. */
  files?: Record<string, BlobFileData>;
};

const DEFAULT_OUTPUT_DIR = '.rstest-reports';

/**
 * Single owner of the on-disk blob filename grammar. The writer (this module)
 * and the merge reader (`mergeReports.ts`) previously encoded the
 * `blob[-index-count].json` shape independently — a string template here and a
 * hand-written regexp there — so a rename would silently desync the two sides.
 */
export const blobFileName = (shard?: ShardConfig): string =>
  shard ? `blob-${shard.index}-${shard.count}.json` : 'blob.json';

export const BLOB_FILE_RE: RegExp = /^blob(-\d+-\d+)?\.json$/;

export const isBlobFile = (name: string): boolean => BLOB_FILE_RE.test(name);

/**
 * Parses a blob file and gates it on the writer's version. Blob payload shapes
 * are internal and unversioned beyond this field, so a skew between shards
 * would silently drop or misread data — reject it instead of merging partially.
 */
export const parseBlobFile = (content: string, fileName: string): BlobData => {
  const blob = JSON.parse(content) as BlobData;
  if (blob.version !== RSTEST_VERSION) {
    throw new Error(
      `Blob report ${color.cyan(fileName)} was generated by Rstest ${color.yellow(blob.version || 'unknown')}, but this is Rstest ${color.yellow(RSTEST_VERSION)}.\n` +
        'Blob reports can only be merged by the version that produced them. Regenerate them with --reporters=blob.',
    );
  }
  return blob;
};

/**
 * Single owner of the `BlobData.files` key grammar: both sides must key through
 * here, never by test path alone — a path is ambiguous once several projects
 * run the same file. `TestFileInfo` carries no project name, so the writer
 * derives it from the collected tree; every other producer has one on its own
 * payload, and the reader takes `TestFileResult.project`.
 */
export const blobFileKey = (
  project: string | undefined,
  testPath: string,
): string => JSON.stringify([project ?? '', testPath]);

export class BlobReporter implements Reporter {
  // Blob output goes to a file, never process stdout/stderr.
  readonly flushOutputStreams = false;

  private readonly config: NormalizedConfig;
  private readonly outputDir: string;
  private readonly untrackedLogs: UserConsoleLog[] = [];
  private readonly files = new Map<string, BlobFileData>();

  constructor({
    rootPath,
    config,
    options,
  }: {
    rootPath: string;
    config: NormalizedConfig;
    options?: BlobReporterOptions;
  }) {
    this.config = config;
    this.outputDir = options?.outputDir
      ? join(rootPath, options.outputDir)
      : join(rootPath, DEFAULT_OUTPUT_DIR);
  }

  onUserConsoleLog(log: UserConsoleLog): void {
    // `project` is optional on the wire; without it a run where several
    // projects share a test path cannot say whose window the log belongs to,
    // so it replays outside any file rather than under the wrong one.
    if (log.project === undefined) {
      this.untrackedLogs.push(log);
      return;
    }
    this.fileData(log.project, log.testPath).events.push({ h: 'log', log });
  }

  onTestFileReady(test: TestFileInfo): void {
    const data = this.fileData(test.tests[0]?.project, test.testPath);
    data.tests = test.tests;
    data.events.push({ h: 'ready' });
  }

  onTestSuiteStart(test: TestSuiteInfo): void {
    this.fileData(test.project, test.testPath).events.push({
      h: 'suiteStart',
      id: test.testId,
    });
  }

  onTestSuiteResult(result: TestResult): void {
    this.fileData(result.project, result.testPath).events.push({
      h: 'suiteResult',
      result,
    });
  }

  onTestCaseStart(test: TestCaseInfo): void {
    this.fileData(test.project, test.testPath).events.push({
      h: 'caseStart',
      id: test.testId,
    });
  }

  onTestCaseResult(result: TestResult): void {
    this.fileData(result.project, result.testPath).events.push({
      h: 'caseResult',
      id: result.testId,
    });
  }

  private fileData(
    project: string | undefined,
    testPath: string,
  ): BlobFileData {
    const key = blobFileKey(project, testPath);
    let data = this.files.get(key);
    if (!data) {
      data = { tests: [], events: [] };
      this.files.set(key, data);
    }
    return data;
  }

  async onTestRunEnd({
    results,
    coverage,
    testResults,
    duration,
    snapshotSummary,
    unhandledErrors,
  }: {
    results: TestFileResult[];
    coverage?: CoverageMapData;
    testResults: TestResult[];
    duration: Duration;
    snapshotSummary: SnapshotSummary;
    unhandledErrors?: Error[];
  }): Promise<void> {
    const shard = this.config.shard;
    const fileName = blobFileName(shard);

    const blobData: BlobData = {
      version: RSTEST_VERSION,
      shard: shard ? { index: shard.index, count: shard.count } : undefined,
      results,
      coverage,
      testResults,
      duration,
      snapshotSummary,
      unhandledErrors: unhandledErrors?.map((e) => ({
        message: e.message,
        stack: e.stack,
        name: e.name,
      })),
      consoleLogs:
        this.untrackedLogs.length > 0 ? this.untrackedLogs : undefined,
      files: Object.fromEntries(this.files),
    };

    mkdirSync(this.outputDir, { recursive: true });
    writeFileSync(
      join(this.outputDir, fileName),
      JSON.stringify(blobData),
      'utf-8',
    );
  }
}
