import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'pathe';
import type {
  CoverageMapData,
  Duration,
  NormalizedConfig,
  Reporter,
  ShardConfig,
  SnapshotSummary,
  TestCaseInfo,
  TestFileInfo,
  TestFileResult,
  TestResult,
  TestSuiteInfo,
  UserConsoleLog,
} from '../types';
import type { BlobReporterOptions } from '../types/reporter';
import { color } from '../utils';

/**
 * One recorded lifecycle event: the hook that fired, with the payload the
 * reporter received, verbatim. Replay is playback, never reconstruction —
 * every payload rebuilt from other blob data has eventually diverged from
 * what the live run emitted (an order a tree walk cannot represent, a
 * `startTime` only the live event carries).
 */
export type BlobFileEvent =
  | { h: 'start' | 'ready'; test: TestFileInfo }
  | { h: 'suiteStart'; test: TestSuiteInfo }
  | { h: 'caseStart'; test: TestCaseInfo }
  | { h: 'suiteResult' | 'caseResult'; result: TestResult }
  | { h: 'log'; log: UserConsoleLog };

/**
 * One file's replay track — what `TestFileResult` cannot carry: `results`
 * holds case results only, with no record of what fired or in what order.
 */
export type BlobFileData = {
  events: BlobFileEvent[];
};

export type BlobData = {
  version: string;
  shard?: ShardConfig;
  results: TestFileResult[];
  coverage?: CoverageMapData;
  testResults: TestResult[];
  duration: Duration;
  snapshotSummary: SnapshotSummary;
  unhandledErrors?: { message: string; stack?: string; name?: string }[];
  /** Keyed by {@link blobFileKey}. */
  files?: Record<string, BlobFileData>;
};

const DEFAULT_OUTPUT_DIR = '.rstest-reports';

/**
 * Single owner of the on-disk blob filename grammar. The writer (this module)
 * and the merge reader (`mergeReports.ts`) previously encoded the
 * `blob[-index-count].json` shape independently — a string template here and a
 * hand-written regexp there — so a rename would silently desync the two sides.
 */
export const blobFileName = (shard?: ShardConfig): string =>
  shard ? `blob-${shard.index}-${shard.count}.json` : 'blob.json';

export const BLOB_FILE_RE: RegExp = /^blob(-\d+-\d+)?\.json$/;

export const isBlobFile = (name: string): boolean => BLOB_FILE_RE.test(name);

/**
 * Parses a blob file and gates it on the writer's version. Blob payload shapes
 * are internal and unversioned beyond this field, so a skew between shards
 * would silently drop or misread data — reject it instead of merging partially.
 */
export const parseBlobFile = (content: string, fileName: string): BlobData => {
  const blob = JSON.parse(content) as BlobData;
  if (blob.version !== RSTEST_VERSION) {
    throw new Error(
      `Blob report ${color.cyan(fileName)} was generated by Rstest ${color.yellow(blob.version || 'unknown')}, but this is Rstest ${color.yellow(RSTEST_VERSION)}.\n` +
        'Blob reports can only be merged by the version that produced them. Regenerate them with --reporters=blob.',
    );
  }
  return blob;
};

/**
 * Single owner of the `BlobData.files` key grammar: both sides must key through
 * here, never by test path alone — a path is ambiguous once several projects
 * run the same file. Every producer carries its project on its own payload;
 * the reader takes `TestFileResult.project`, or parses the project back out
 * of the key when a track has no result.
 */
export const blobFileKey = (project: string, testPath: string): string =>
  JSON.stringify([project, testPath]);

/** Inverse of {@link blobFileKey}, for tracks the reader must key-walk. */
export const parseBlobFileKey = (
  key: string,
): { project: string; testPath: string } => {
  const [project, testPath] = JSON.parse(key) as [string, string];
  return { project, testPath };
};

export class BlobReporter implements Reporter {
  // Blob output goes to a file, never process stdout/stderr.
  readonly flushOutputStreams = false;

  private readonly config: NormalizedConfig;
  private readonly outputDir: string;
  private readonly files = new Map<string, BlobFileData>();
  private readonly staleKeys = new Set<string>();

  constructor({
    rootPath,
    config,
    options,
  }: {
    rootPath: string;
    config: NormalizedConfig;
    options?: BlobReporterOptions;
  }) {
    this.config = config;
    this.outputDir = options?.outputDir
      ? join(rootPath, options.outputDir)
      : join(rootPath, DEFAULT_OUTPUT_DIR);
  }

  onTestRunStart(): void {
    // A track lives for one run cycle: `onTestRunEnd` carries the latest
    // result per file across watch reruns, so a rerun file's track must be
    // recorded anew — appending would replay both runs against one result.
    // Marking (rather than clearing) keeps tracks of files the rerun does not
    // touch, whose results the final blob still carries, and lets the file's
    // first event of the cycle do the replacement — which may be a log emitted
    // during environment setup, before the file ever starts. (A file
    // bail-skipped during a watch rerun keeps its previous cycle's track
    // alongside its new skip result — a known non-goal: nothing fires for the
    // skip, and blob-in-watch is a fringe pairing.)
    for (const key of this.files.keys()) {
      this.staleKeys.add(key);
    }
  }

  onTestFileStart(test: TestFileInfo): void {
    this.fileData(test.project, test.testPath).events.push({
      h: 'start',
      test,
    });
  }

  onUserConsoleLog(log: UserConsoleLog): void {
    this.fileData(log.project, log.testPath).events.push({ h: 'log', log });
  }

  onTestFileReady(test: TestFileInfo): void {
    this.fileData(test.project, test.testPath).events.push({
      h: 'ready',
      test,
    });
  }

  onTestSuiteStart(test: TestSuiteInfo): void {
    this.fileData(test.project, test.testPath).events.push({
      h: 'suiteStart',
      test,
    });
  }

  onTestSuiteResult(result: TestResult): void {
    this.fileData(result.project, result.testPath).events.push({
      h: 'suiteResult',
      result,
    });
  }

  onTestCaseStart(test: TestCaseInfo): void {
    this.fileData(test.project, test.testPath).events.push({
      h: 'caseStart',
      test,
    });
  }

  onTestCaseResult(result: TestResult): void {
    this.fileData(result.project, result.testPath).events.push({
      h: 'caseResult',
      result,
    });
  }

  private fileData(project: string, testPath: string): BlobFileData {
    const key = blobFileKey(project, testPath);
    const stale = this.staleKeys.delete(key);
    let data = this.files.get(key);
    if (!data || stale) {
      data = { events: [] };
      this.files.set(key, data);
    }
    return data;
  }

  async onTestRunEnd({
    results,
    coverage,
    testResults,
    duration,
    snapshotSummary,
    unhandledErrors,
  }: {
    results: TestFileResult[];
    coverage?: CoverageMapData;
    testResults: TestResult[];
    duration: Duration;
    snapshotSummary: SnapshotSummary;
    unhandledErrors?: Error[];
  }): Promise<void> {
    const shard = this.config.shard;
    const fileName = blobFileName(shard);

    const blobData: BlobData = {
      version: RSTEST_VERSION,
      shard: shard ? { index: shard.index, count: shard.count } : undefined,
      results,
      coverage,
      testResults,
      duration,
      snapshotSummary,
      unhandledErrors: unhandledErrors?.map((e) => ({
        message: e.message,
        stack: e.stack,
        name: e.name,
      })),
      files: Object.fromEntries(this.files),
    };

    mkdirSync(this.outputDir, { recursive: true });
    writeFileSync(
      join(this.outputDir, fileName),
      JSON.stringify(blobData),
      'utf-8',
    );
  }
}
