import { existsSync } from 'node:fs';
import * as path from 'node:path';
import { RspackCLI } from '@rspack/cli';
import type {
  Configuration,
  MultiRspackOptions,
  RspackOptions,
} from '@rspack/core';
import type { ExtendConfig, ExtendConfigFn } from '@rstest/core';

type RspackConfig = RspackOptions | MultiRspackOptions;

type RspackConfigName = string;

const DEFAULT_CONFIG_BASENAME = 'rspack.config';
const DEFAULT_EXTENSIONS = ['.js', '.ts', '.mjs', '.mts', '.cjs', '.cts'];

export interface WithRspackConfigOptions {
  /**
   * Working directory used to resolve config path.
   * @default process.cwd()
   */
  cwd?: string;
  /**
   * Path to rspack config file.
   * @default './rspack.config.ts'
   */
  configPath?: string;
  /**
   * Select named config when using multiple Rspack configs.
   */
  configName?: RspackConfigName;
  /**
   * Environment values passed to Rspack config function.
   */
  env?: Record<string, unknown> | string[];
  /**
   * `NODE_ENV` value used when loading config.
   */
  nodeEnv?: string;
  /**
   * Modify Rspack config before converting to rstest config.
   */
  modifyRspackConfig?: (config: RspackOptions) => RspackOptions;
}

const findDefaultConfig = (cwd: string): string | null => {
  const basePath = path.resolve(cwd, DEFAULT_CONFIG_BASENAME);
  for (const ext of DEFAULT_EXTENSIONS) {
    const candidate = `${basePath}${ext}`;
    if (existsSync(candidate)) {
      return candidate;
    }
  }
  return null;
};

const normalizeTargets = (target: RspackOptions['target']): string[] => {
  if (!target) {
    return [];
  }
  if (Array.isArray(target)) {
    return target.filter(Boolean) as string[];
  }
  if (typeof target === 'string') {
    return [target];
  }
  return [];
};

const isNodeTarget = (targets: string[]): boolean =>
  targets.some(
    (target) => target === 'async-node' || target.startsWith('node'),
  );

const isHtmlRspackPlugin = (plugin: unknown): boolean =>
  plugin && (plugin as { constructor?: { name?: string } }).constructor
    ? (plugin as { constructor: { name?: string } }).constructor.name ===
      'HtmlRspackPlugin'
    : false;

/**
 * Build rspack tool config function that applies user's rspack config
 * onto the base config generated by rstest/rsbuild.
 *
 * Properties already extracted to rstest-native config (resolve, output, etc.)
 * are excluded to avoid double-merging.
 */
const buildRspackToolConfig = (
  rspackConfig: RspackOptions,
): ((config: Configuration) => Configuration) => {
  // lazyCompilation is only supported in browser mode, strip it
  const { lazyCompilation: _lazy, ...restConfig } = rspackConfig;

  return (config: Configuration): Configuration => {
    const nextConfig: Configuration = { ...config };

    // Module rules: concatenate user's rules with base rules
    if (restConfig.module) {
      const baseModule = config.module || {};
      const merged = { ...baseModule, ...restConfig.module };
      if (baseModule.rules || restConfig.module.rules) {
        merged.rules = [
          ...(baseModule.rules || []),
          ...(restConfig.module.rules || []),
        ];
      }
      nextConfig.module = merged;
    }

    // Plugins: filter out HtmlRspackPlugin (rsbuild manages HTML)
    if (restConfig.plugins?.length) {
      const plugins = restConfig.plugins.filter(
        (plugin) => plugin && !isHtmlRspackPlugin(plugin),
      );
      nextConfig.plugins = [...(config.plugins || []), ...plugins];
    }

    // Merge remaining rspack-only properties
    if (restConfig.experiments) {
      nextConfig.experiments = {
        ...(config.experiments || {}),
        ...restConfig.experiments,
      };
    }

    if (restConfig.optimization) {
      nextConfig.optimization = {
        ...(config.optimization || {}),
        ...restConfig.optimization,
      };
    }

    if (restConfig.output) {
      const baseOutput = config.output || {};
      const mergedOutput = { ...baseOutput, ...restConfig.output };
      // Preserve rstest's output path
      if (baseOutput.path) {
        mergedOutput.path = baseOutput.path;
      }
      nextConfig.output = mergedOutput;
    }

    if (restConfig.devtool !== undefined) {
      nextConfig.devtool = restConfig.devtool;
    }

    if (restConfig.watchOptions) {
      nextConfig.watchOptions = {
        ...(config.watchOptions || {}),
        ...restConfig.watchOptions,
      };
    }

    if (restConfig.snapshot !== undefined) {
      nextConfig.snapshot = restConfig.snapshot;
    }

    if (restConfig.externalsPresets) {
      nextConfig.externalsPresets = {
        ...(config.externalsPresets || {}),
        ...restConfig.externalsPresets,
      };
    }

    if (restConfig.cache !== undefined) {
      nextConfig.cache = restConfig.cache;
    }

    return nextConfig;
  };
};

const selectRspackConfig = (
  config: RspackConfig,
  configName?: string,
): RspackOptions => {
  const configs = Array.isArray(config) ? config : [config];

  if (configs.length === 0) {
    throw new Error('No Rspack configuration found.');
  }

  if (!configName) {
    return configs[0] || {};
  }

  const found = configs.find((item) => item?.name === configName);
  if (!found) {
    throw new Error(
      `Configuration with the name "${configName}" was not found.`,
    );
  }
  return found;
};

const resolveConfigPath = (cwd: string, configPath?: string): string | null => {
  if (configPath) {
    return path.isAbsolute(configPath)
      ? configPath
      : path.resolve(cwd, configPath);
  }
  return findDefaultConfig(cwd);
};

const loadRspackConfig = async (
  options: WithRspackConfigOptions,
): Promise<RspackConfig | null> => {
  const cwd = options.cwd ?? process.cwd();
  const configFile = resolveConfigPath(cwd, options.configPath);

  if (!configFile || !existsSync(configFile)) {
    return null;
  }

  const cli = new RspackCLI();
  const { config } = await cli.loadConfig({
    config: configFile,
    env: options.env,
    nodeEnv: options.nodeEnv,
  });

  return config as RspackConfig;
};

export function toRstestConfig({
  rspackConfig,
  configName,
  modifyRspackConfig,
}: {
  rspackConfig: RspackOptions;
  configName?: RspackConfigName;
  modifyRspackConfig?: (config: RspackOptions) => RspackOptions;
}): ExtendConfig {
  const finalConfig = modifyRspackConfig
    ? modifyRspackConfig(rspackConfig)
    : rspackConfig;

  const targets = normalizeTargets(finalConfig.target);
  const testEnvironment = isNodeTarget(targets) ? 'node' : 'happy-dom';

  // Extract resolve config — rspack's ResolveOptions is mostly compatible
  // with rsbuild's resolve type, cast to align minor differences (e.g. alias: false)
  const resolve = finalConfig.resolve as ExtendConfig['resolve'];

  // Extract output.module — the only rspack output property supported by rstest
  const outputModule = finalConfig.output?.module;
  const output =
    outputModule !== undefined ? { module: outputModule } : undefined;

  // Extract tsconfigPath from rspack's resolve.tsConfig
  const tsConfig = finalConfig.resolve?.tsConfig;
  const tsconfigPath =
    typeof tsConfig === 'string'
      ? tsConfig
      : (tsConfig as { configFile?: string } | undefined)?.configFile;
  const source = tsconfigPath ? { tsconfigPath } : undefined;

  return {
    name: configName ?? finalConfig.name,
    ...(output ? { output } : {}),
    ...(source ? { source } : {}),
    ...(resolve ? { resolve } : {}),
    plugins: [
      {
        name: 'remove-rsbuild-css',
        remove: ['rsbuild:css', 'rsbuild:less', 'rsbuild:sass'],
        setup: () => {},
      },
    ],
    tools: {
      rspack: buildRspackToolConfig(finalConfig),
    } as ExtendConfig['tools'],
    testEnvironment,
  };
}

export function withRspackConfig(
  options: WithRspackConfigOptions = {},
): ExtendConfigFn {
  return async () => {
    const config = await loadRspackConfig(options);

    if (!config) {
      return {};
    }

    const selectedConfig = selectRspackConfig(config, options.configName);

    return toRstestConfig({
      rspackConfig: selectedConfig,
      configName: options.configName,
      modifyRspackConfig: options.modifyRspackConfig,
    });
  };
}
