name: Release VS Code Extension

on:
  workflow_dispatch: {}

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          [
            win32-x64,
            win32-arm64,
            darwin-x64,
            darwin-arm64,
            linux-x64,
            linux-arm64,
            linux-armhf,
            alpine-x64,
            alpine-arm64,
          ]
    defaults:
      run:
        working-directory: packages/vscode
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

      - name: Unit tests
        run: npm run test:unit

      - name: Build
        run: npm run build

      - name: Publish to VS Code Marketplace (target)
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: npx vsce publish --target ${{ matrix.target }}
