name: Release

on:
  workflow_dispatch:
    inputs:
      npm_tag:
        type: choice
        description: 'Specify npm tag'
        required: true
        default: 'alpha'
        options:
          - alpha
          - beta
          - rc
          - canary
          - latest
      branch:
        description: 'Branch to release'
        required: true
        default: 'main'

permissions:
  # Provenance generation in GitHub Actions requires "write" access to the "id-token"
  id-token: write

jobs:
  release:
    name: Release
    if: github.repository == 'web-infra-dev/rstest' && github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    environment: npm
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          check-latest: true
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      # Update npm to the latest version to enable OIDC
      - name: Update npm
        run: |
          npm install -g npm@latest
          npm --version

      - name: Install Dependencies
        run: pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Publish to npm
        run: |
          pnpm --filter './packages/*' -r stage publish --tag ${{ github.event.inputs.npm_tag }} --no-git-checks

  release_vscode_extension:
    name: Release VS Code Extension (${{ matrix.vsce-target }})
    if: github.repository == 'web-infra-dev/rstest' && github.event_name == 'workflow_dispatch'
    needs: release
    runs-on: ${{ matrix.runner }}
    environment: vscode-marketplace
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            vsce-target: linux-x64
            arch: x64
          - runner: ubuntu-22.04
            vsce-target: linux-arm64
            arch: arm64
          - runner: macos-15
            vsce-target: darwin-x64
            arch: x64
          - runner: macos-15
            vsce-target: darwin-arm64
            arch: arm64
          - runner: windows-2022
            vsce-target: win32-x64
            arch: x64
          - runner: windows-latest
            vsce-target: win32-arm64
            arch: arm64
    defaults:
      run:
        shell: bash
    env:
      VSCE_TARGET: ${{ matrix.vsce-target }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          fetch-depth: 1
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Pnpm
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 22
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: |
          pnpm config set --location=project --json supportedArchitectures '{"cpu":["current","${{ matrix.arch }}"]}'
          pnpm install

      - name: Build Packages
        run: pnpm run build

      - name: Package VS Code Extension
        run: pnpm --filter ./packages/vscode run package:vsce -o "rstest-${{ matrix.vsce-target }}.vsix"

      - name: Publish VS Code Extension
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
        run: pnpm --filter ./packages/vscode exec vsce publish --target ${{ matrix.vsce-target }} --skip-duplicate

      - name: Publish OVSX Extension
        env:
          OVSX_PAT: ${{ secrets.OVSX_PAT }}
        run: pnpm --filter ./packages/vscode exec ovsx publish --target ${{ matrix.vsce-target }} --skip-duplicate
